### ISSUE TITLE
link

### ISSUE THREAD

**Issue by borgr** [shashiongithub/Split-and-Rephrase#1]
Hey it might be minor but perhaps not minor to you.
The link in the readme got me to Neural Response Generation via GAN with an Approximate
Embedding Layer

I think you should use something like this https://arxiv.org/pdf/1707.06971.pdf (or another link to acl or wherever you want)
instead of
http://aclweb.org/anthology/D/D17/D17-1065.pdf

**Comment by shashiongithub** [comment]
Thanks! I have fixed it now.

**Comment by borgr** [comment]
Works, closing the issue.

Offtopic: I also sent you a mail and a pull request (for small things I could change by myself, unlike this one)
