### ISSUE TITLE
looking for a dataset explanation

### ISSUE THREAD

**Issue by LifangD** [shashiongithub/Split-and-Rephrase#5]
Hi,  is there any explanation about  the  final-complexsimple-meanpreserve-intreeorder-full.txt
"COMPLEX-1:MR-1:SIMPLE-1:SPTYPE-1-1:MR-1" is a little difficult for me to understand...

**Comment by shashiongithub** [comment]
Let me give an example (see below) from the dataset: 

The "COMPLEX" sentence with id "346" could have various meaning representations ("MR"s). 

COMPLEX-346:MR-1
category=City eid=Id106 size=2

or 

COMPLEX-346:MR-2
category=City eid=Id138 size=3

One representation has 2 RDF triples in it (size=2) and another one has 2 RDF triples in it (size=3).

There are 4 simplified version of "COMPLEX-346:MR-1".

COMPLEX-346:MR-1:SIMPLE-1
COMPLEX-346:MR-1:SIMPLE-2
COMPLEX-346:MR-1:SIMPLE-3
COMPLEX-346:MR-1:SIMPLE-4

Similarly for "COMPLEX-346:MR-2". 

Each of COMPLEX-346:MR-1:SIMPLE-* could have their own ways of splitting COMPLEX-346:MR-1. 

Split type ("SPTYPE") is defined as the number of RDF triples in each subset after the split. For example, "COMPLEX-346:MR-1" has two RDF triples. Hence their can be only one split type: "SPTYPE-1-1". But "COMPLEX-346:MR-2" has three RDF triples, simplified version of "COMPLEX-346:MR-2" could have "SPTYPE-1-1-1" or "SPTYPE-1-2". 

COMPLEX-346:MR-1:SIMPLE-*:SPTYPE-1-1
COMPLEX-346:MR-2:SIMPLE-1:SPTYPE-1-1-1
COMPLEX-346:MR-2:SIMPLE-2:SPTYPE-1-2

"SPTYPE-1-2" could have different ways to splitting "COMPLEX-346:MR-2", e.g. [R1, (R2, R3)] or [R2, {R1, R3)]. Hence, they could have different meaning representations ("MR").  

COMPLEX-346:MR-1:SIMPLE-*:SPTYPE-1-1:MR-1

and so on.

== Example ==

COMPLEX-346
Most of Atlanta is part of DeKalb County in Georgia , United States .

COMPLEX-346:MR-1
category=City eid=Id106 size=2

COMPLEX-346:MR-1:SIMPLE-1
Most of Atlanta is part of DeKalb County in Georgia .
Atlanta is in the U.S.

COMPLEX-346:MR-1:SIMPLE-1:SPTYPE-1-1:MR-1
category=City eid=Id140 size=1
Most of Atlanta is part of DeKalb County in Georgia .
category=City eid=Id138 size=1
Atlanta is in the U.S.

COMPLEX-346:MR-1:SIMPLE-2
Most of Atlanta is part of DeKalb County in Georgia .
Atlanta is in the United States .

COMPLEX-346:MR-1:SIMPLE-2:SPTYPE-1-1:MR-1
category=City eid=Id140 size=1
Most of Atlanta is part of DeKalb County in Georgia .
category=City eid=Id138 size=1
Atlanta is in the United States .

COMPLEX-346:MR-1:SIMPLE-3
Atlanta is part of DeKalb County in Georgia .
Atlanta is in the U.S.

COMPLEX-346:MR-1:SIMPLE-3:SPTYPE-1-1:MR-1
category=City eid=Id140 size=1
Atlanta is part of DeKalb County in Georgia .
category=City eid=Id138 size=1
Atlanta is in the U.S.

COMPLEX-346:MR-1:SIMPLE-4
Atlanta is part of DeKalb County in Georgia .
Atlanta is in the United States .

COMPLEX-346:MR-1:SIMPLE-4:SPTYPE-1-1:MR-1
category=City eid=Id140 size=1
Atlanta is part of DeKalb County in Georgia .
category=City eid=Id138 size=1
Atlanta is in the United States .

COMPLEX-346:MR-2
category=City eid=Id138 size=3

COMPLEX-346:MR-2:SIMPLE-1
Most of Atlanta is part of DeKalb County in Georgia .
DeKalb County , Georgia , is located in the United States .
Atlanta is part of Georgia .

COMPLEX-346:MR-2:SIMPLE-1:SPTYPE-1-1-1:MR-1
category=City eid=Id140 size=1
Most of Atlanta is part of DeKalb County in Georgia .
category=City eid=Id195 size=1
DeKalb County , Georgia , is located in the United States .
category=City eid=Id139 size=1
Atlanta is part of Georgia .

COMPLEX-346:MR-2:SIMPLE-2
DeKalb County , Georgia is in the United States .
Atlanta is part of DeKalb County which is located in Georgia .

COMPLEX-346:MR-2:SIMPLE-2:SPTYPE-1-2:MR-1
category=City eid=Id195 size=1
DeKalb County , Georgia is in the United States .
category=City eid=Id105 size=2
Atlanta is part of DeKalb County which is located in Georgia .

COMPLEX-346:MR-2:SIMPLE-3
Most of Atlanta is part of DeKalb County in Georgia which is located in the United States of America .
Atlanta is part of Georgia .

**Comment by LifangD** [comment]
Thanks for your patience, and another small question is about category and eid, is it the entry info from DBpedia?

**Comment by shashiongithub** [comment]
It is an MR id referring to an entry in the WebNLG corpus ("webnlg-corpus-release"). This is also released with the dataset.

**Comment by LifangD** [comment]
@shashiongithub thanks a lot!
